---
name: EVE
on:
  pull_request_target:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test
        run: |
          make test
      - name: Report test results as Annotations
        if: ${{ always() }}
        uses: guyarb/golang-test-annoations@v0.1
        with:
          test-results: dist/amd64/results.json
      - name: Store raw test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: 'test-report'
          path: ${{ github.workspace }}/dist

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Adjust Version
        run: |
          git tag -a -m0.0.0-pr-${{ github.event.pull_request.number  }} 0.0.0-pr-${{ github.event.pull_request.number  }}
          echo build > /tmp/target
      - name: Build packages
        run: |
          make pkgs
      - name: Login into DockerHUB
        if: github.actor == 'rvs' || github.actor == 'eriknordmark'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u evebuild --password-stdin
          echo push > /tmp/target
      - name: Build EVE
        run: |
          make LINUXKIT_PKG_TARGET="$(cat /tmp/target)" eve
      - name: Build EVE for KVM
        run: |
          rm -rf dist
          make LINUXKIT_PKG_TARGET="$(cat /tmp/target)" HV=kvm eve

# If all else fails, you may find solace here
#  https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
#  https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
#
#  echo "::error file=${file},line=${linenum},col=${column}::${plugin}:${text}"
#  echo "::error file=${file},line=${linenum}::${plugin}:${text}"
#
#  dump:
#      runs-on: ubuntu-latest
#      steps:
#        - name: Dump GitHub context
#          env:
#            GITHUB_CONTEXT: ${{ toJson(github) }}
#          run: |
#            echo "$GITHUB_CONTEXT"
#            echo ${{ github.event.pull_request.title }}
